### PR TITLE
Add support for Bluetooth MAC addresses

### PR DESCRIPTION
**Pull request by rrooggiieerr**
Hi William,

I've added Bluetooth MAC address support in addition to tty name/path. It's needed to use the library in HA.

Let me know what you think

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
I'm just closed this pull request for now as it seems that latest HA OS uses Python 3.10 and pybluez does not work with Python 3.10. Going to rewrite the code to use Python sockets

**Comment by rrooggiieerr** [comment]
Well, that wasn't actually to difficult to fix. Please review and let me know what you think

**Comment by valletw** [comment]
Hi,
I took the time to have a look to your modification.
I create a new branch `add-interface` with a more maintainable implementation by using interface class provided to the meter class.
Currently, my laptops cannot run the demo:
- On MacOS doesn't support the bluetooth socket, so the import fails
- On Ubuntu, I had a "Host is down" error...
And I also need to fix the CI with python import issue.

**Comment by rrooggiieerr** [comment]
I also don't have it working on my MacBook, but it works on Raspberry Pi OS. I still have some connection issues, I maigh come up with some additional change requests

**Pull request closed without merging**
